// THIS FILE IS AUTO-GENERATED BY generator21.py. DO NOT EDIT.

#pragma once

#include "Types21.h"
#include "TFJson.h"

#include <math.h>
#include <string.h>

#ifndef OCPP_INTEGER_NOT_PASSED
#define OCPP_INTEGER_NOT_PASSED INT32_MAX
#endif
#ifndef OCPP_DECIMAL_NOT_PASSED
#define OCPP_DECIMAL_NOT_PASSED NAN
#endif
#ifndef OCPP_DATETIME_NOT_PASSED
#define OCPP_DATETIME_NOT_PASSED 0
#endif

namespace Ocpp21 {

class ChargePoint21;

extern uint64_t next_call_id;

extern const char * const BootNotificationReasonStrings[];

enum class BootNotificationReason : uint8_t {
    APPLICATION_RESET,
    FIRMWARE_UPDATE,
    LOCAL_RESET,
    POWER_UP,
    REMOTE_RESET,
    SCHEDULED_RESET,
    TRIGGERED,
    UNKNOWN,
    WATCHDOG,
    NONE
};

extern const char * const StatusNotificationConnectorStatusStrings[];

enum class StatusNotificationConnectorStatus : uint8_t {
    AVAILABLE,
    OCCUPIED,
    RESERVED,
    UNAVAILABLE,
    FAULTED,
    NONE
};

extern const char * const GetBaseReportResponseStatusStrings[];

enum class GetBaseReportResponseStatus : uint8_t {
    ACCEPTED,
    REJECTED,
    NOT_SUPPORTED,
    EMPTY_RESULT_SET,
    NONE
};

extern const char * const TriggerMessageResponseStatusStrings[];

enum class TriggerMessageResponseStatus : uint8_t {
    ACCEPTED,
    REJECTED,
    NOT_IMPLEMENTED,
    NONE
};

extern const char * const ResetResponseStatusStrings[];

enum class ResetResponseStatus : uint8_t {
    ACCEPTED,
    REJECTED,
    SCHEDULED,
    NONE
};

extern const char * const BootNotificationResponseStatusStrings[];

enum class BootNotificationResponseStatus : uint8_t {
    ACCEPTED,
    PENDING,
    REJECTED
};

extern const char * const AttributeEnumTypeStrings[];

enum class AttributeEnumType : uint8_t {
    ACTUAL,
    TARGET,
    MIN_SET,
    MAX_SET
};

extern const char * const GetBaseReportReportBaseStrings[];

enum class GetBaseReportReportBase : uint8_t {
    CONFIGURATION_INVENTORY,
    FULL_INVENTORY,
    SUMMARY_INVENTORY
};

extern const char * const TriggerMessageRequestedMessageStrings[];

enum class TriggerMessageRequestedMessage : uint8_t {
    BOOT_NOTIFICATION,
    LOG_STATUS_NOTIFICATION,
    FIRMWARE_STATUS_NOTIFICATION,
    HEARTBEAT,
    METER_VALUES,
    SIGN_CHARGING_STATION_CERTIFICATE,
    SIGN_V2_G_CERTIFICATE,
    SIGN_V2_G20_CERTIFICATE,
    STATUS_NOTIFICATION,
    TRANSACTION_EVENT,
    SIGN_COMBINED_CERTIFICATE,
    PUBLISH_FIRMWARE_STATUS_NOTIFICATION,
    CUSTOM_TRIGGER
};

extern const char * const ResetTypeStrings[];

enum class ResetType : uint8_t {
    IMMEDIATE,
    ON_IDLE,
    IMMEDIATE_AND_RESUME
};

extern const char * const GetVariablesResponseGetVariableResultAttributeStatusStrings[];

enum class GetVariablesResponseGetVariableResultAttributeStatus : uint8_t {
    ACCEPTED,
    REJECTED,
    UNKNOWN_COMPONENT,
    UNKNOWN_VARIABLE,
    NOT_SUPPORTED_ATTRIBUTE_TYPE,
    NONE
};

extern const char * const GetVariableResultAttributeEnumTypeStrings[];

enum class GetVariableResultAttributeEnumType : uint8_t {
    ACTUAL,
    TARGET,
    MIN_SET,
    MAX_SET,
    NONE
};

extern const char * const SetVariablesResponseSetVariableResultAttributeStatusStrings[];

enum class SetVariablesResponseSetVariableResultAttributeStatus : uint8_t {
    ACCEPTED,
    REJECTED,
    UNKNOWN_COMPONENT,
    UNKNOWN_VARIABLE,
    NOT_SUPPORTED_ATTRIBUTE_TYPE,
    REBOOT_REQUIRED,
    NONE
};

extern const char * const CallActionStrings[];

enum class CallAction : uint8_t {
    AFRR_SIGNAL,
    AFRR_SIGNAL_RESPONSE,
    ADJUST_PERIODIC_EVENT_STREAM,
    ADJUST_PERIODIC_EVENT_STREAM_RESPONSE,
    AUTHORIZE,
    AUTHORIZE_RESPONSE,
    BATTERY_SWAP,
    BATTERY_SWAP_RESPONSE,
    BOOT_NOTIFICATION,
    BOOT_NOTIFICATION_RESPONSE,
    CANCEL_RESERVATION,
    CANCEL_RESERVATION_RESPONSE,
    CERTIFICATE_SIGNED,
    CERTIFICATE_SIGNED_RESPONSE,
    CHANGE_AVAILABILITY,
    CHANGE_AVAILABILITY_RESPONSE,
    CHANGE_TRANSACTION_TARIFF,
    CHANGE_TRANSACTION_TARIFF_RESPONSE,
    CLEAR_CACHE,
    CLEAR_CACHE_RESPONSE,
    CLEAR_CHARGING_PROFILE,
    CLEAR_CHARGING_PROFILE_RESPONSE,
    CLEAR_DER_CONTROL,
    CLEAR_DER_CONTROL_RESPONSE,
    CLEAR_DISPLAY_MESSAGE,
    CLEAR_DISPLAY_MESSAGE_RESPONSE,
    CLEAR_TARIFFS,
    CLEAR_TARIFFS_RESPONSE,
    CLEAR_VARIABLE_MONITORING,
    CLEAR_VARIABLE_MONITORING_RESPONSE,
    CLEARED_CHARGING_LIMIT,
    CLEARED_CHARGING_LIMIT_RESPONSE,
    CLOSE_PERIODIC_EVENT_STREAM,
    CLOSE_PERIODIC_EVENT_STREAM_RESPONSE,
    COST_UPDATED,
    COST_UPDATED_RESPONSE,
    CUSTOMER_INFORMATION,
    CUSTOMER_INFORMATION_RESPONSE,
    DATA_TRANSFER,
    DATA_TRANSFER_RESPONSE,
    DELETE_CERTIFICATE,
    DELETE_CERTIFICATE_RESPONSE,
    FIRMWARE_STATUS_NOTIFICATION,
    FIRMWARE_STATUS_NOTIFICATION_RESPONSE,
    GET15118_EV_CERTIFICATE,
    GET15118_EV_CERTIFICATE_RESPONSE,
    GET_BASE_REPORT,
    GET_BASE_REPORT_RESPONSE,
    GET_CERTIFICATE_CHAIN_STATUS,
    GET_CERTIFICATE_CHAIN_STATUS_RESPONSE,
    GET_CERTIFICATE_STATUS,
    GET_CERTIFICATE_STATUS_RESPONSE,
    GET_CHARGING_PROFILES,
    GET_CHARGING_PROFILES_RESPONSE,
    GET_COMPOSITE_SCHEDULE,
    GET_COMPOSITE_SCHEDULE_RESPONSE,
    GET_DER_CONTROL,
    GET_DER_CONTROL_RESPONSE,
    GET_DISPLAY_MESSAGES,
    GET_DISPLAY_MESSAGES_RESPONSE,
    GET_INSTALLED_CERTIFICATE_IDS,
    GET_INSTALLED_CERTIFICATE_IDS_RESPONSE,
    GET_LOCAL_LIST_VERSION,
    GET_LOCAL_LIST_VERSION_RESPONSE,
    GET_LOG,
    GET_LOG_RESPONSE,
    GET_MONITORING_REPORT,
    GET_MONITORING_REPORT_RESPONSE,
    GET_PERIODIC_EVENT_STREAM,
    GET_PERIODIC_EVENT_STREAM_RESPONSE,
    GET_REPORT,
    GET_REPORT_RESPONSE,
    GET_TARIFFS,
    GET_TARIFFS_RESPONSE,
    GET_TRANSACTION_STATUS,
    GET_TRANSACTION_STATUS_RESPONSE,
    GET_VARIABLES,
    GET_VARIABLES_RESPONSE,
    HEARTBEAT,
    HEARTBEAT_RESPONSE,
    INSTALL_CERTIFICATE,
    INSTALL_CERTIFICATE_RESPONSE,
    LOG_STATUS_NOTIFICATION,
    LOG_STATUS_NOTIFICATION_RESPONSE,
    METER_VALUES,
    METER_VALUES_RESPONSE,
    NOTIFY_ALLOWED_ENERGY_TRANSFER,
    NOTIFY_ALLOWED_ENERGY_TRANSFER_RESPONSE,
    NOTIFY_CHARGING_LIMIT,
    NOTIFY_CHARGING_LIMIT_RESPONSE,
    NOTIFY_CUSTOMER_INFORMATION,
    NOTIFY_CUSTOMER_INFORMATION_RESPONSE,
    NOTIFY_DER_ALARM,
    NOTIFY_DER_ALARM_RESPONSE,
    NOTIFY_DER_START_STOP,
    NOTIFY_DER_START_STOP_RESPONSE,
    NOTIFY_DISPLAY_MESSAGES,
    NOTIFY_DISPLAY_MESSAGES_RESPONSE,
    NOTIFY_EV_CHARGING_NEEDS,
    NOTIFY_EV_CHARGING_NEEDS_RESPONSE,
    NOTIFY_EV_CHARGING_SCHEDULE,
    NOTIFY_EV_CHARGING_SCHEDULE_RESPONSE,
    NOTIFY_EVENT,
    NOTIFY_EVENT_RESPONSE,
    NOTIFY_MONITORING_REPORT,
    NOTIFY_MONITORING_REPORT_RESPONSE,
    NOTIFY_PERIODIC_EVENT_STREAM,
    NOTIFY_PRIORITY_CHARGING,
    NOTIFY_PRIORITY_CHARGING_RESPONSE,
    NOTIFY_REPORT,
    NOTIFY_REPORT_RESPONSE,
    NOTIFY_SETTLEMENT,
    NOTIFY_SETTLEMENT_RESPONSE,
    NOTIFY_WEB_PAYMENT_STARTED,
    NOTIFY_WEB_PAYMENT_STARTED_RESPONSE,
    OPEN_PERIODIC_EVENT_STREAM,
    OPEN_PERIODIC_EVENT_STREAM_RESPONSE,
    PUBLISH_FIRMWARE,
    PUBLISH_FIRMWARE_RESPONSE,
    PUBLISH_FIRMWARE_STATUS_NOTIFICATION,
    PUBLISH_FIRMWARE_STATUS_NOTIFICATION_RESPONSE,
    PULL_DYNAMIC_SCHEDULE_UPDATE,
    PULL_DYNAMIC_SCHEDULE_UPDATE_RESPONSE,
    REPORT_CHARGING_PROFILES,
    REPORT_CHARGING_PROFILES_RESPONSE,
    REPORT_DER_CONTROL,
    REPORT_DER_CONTROL_RESPONSE,
    REQUEST_BATTERY_SWAP,
    REQUEST_BATTERY_SWAP_RESPONSE,
    REQUEST_START_TRANSACTION,
    REQUEST_START_TRANSACTION_RESPONSE,
    REQUEST_STOP_TRANSACTION,
    REQUEST_STOP_TRANSACTION_RESPONSE,
    RESERVATION_STATUS_UPDATE,
    RESERVATION_STATUS_UPDATE_RESPONSE,
    RESERVE_NOW,
    RESERVE_NOW_RESPONSE,
    RESET,
    RESET_RESPONSE,
    SECURITY_EVENT_NOTIFICATION,
    SECURITY_EVENT_NOTIFICATION_RESPONSE,
    SEND_LOCAL_LIST,
    SEND_LOCAL_LIST_RESPONSE,
    SET_CHARGING_PROFILE,
    SET_CHARGING_PROFILE_RESPONSE,
    SET_DER_CONTROL,
    SET_DER_CONTROL_RESPONSE,
    SET_DEFAULT_TARIFF,
    SET_DEFAULT_TARIFF_RESPONSE,
    SET_DISPLAY_MESSAGE,
    SET_DISPLAY_MESSAGE_RESPONSE,
    SET_MONITORING_BASE,
    SET_MONITORING_BASE_RESPONSE,
    SET_MONITORING_LEVEL,
    SET_MONITORING_LEVEL_RESPONSE,
    SET_NETWORK_PROFILE,
    SET_NETWORK_PROFILE_RESPONSE,
    SET_VARIABLE_MONITORING,
    SET_VARIABLE_MONITORING_RESPONSE,
    SET_VARIABLES,
    SET_VARIABLES_RESPONSE,
    SIGN_CERTIFICATE,
    SIGN_CERTIFICATE_RESPONSE,
    STATUS_NOTIFICATION,
    STATUS_NOTIFICATION_RESPONSE,
    TRANSACTION_EVENT,
    TRANSACTION_EVENT_RESPONSE,
    TRIGGER_MESSAGE,
    TRIGGER_MESSAGE_RESPONSE,
    UNLOCK_CONNECTOR,
    UNLOCK_CONNECTOR_RESPONSE,
    UNPUBLISH_FIRMWARE,
    UNPUBLISH_FIRMWARE_RESPONSE,
    UPDATE_DYNAMIC_SCHEDULE,
    UPDATE_DYNAMIC_SCHEDULE_RESPONSE,
    UPDATE_FIRMWARE,
    UPDATE_FIRMWARE_RESPONSE,
    USE_PRIORITY_CHARGING,
    USE_PRIORITY_CHARGING_RESPONSE,
    VAT_NUMBER_VALIDATION,
    VAT_NUMBER_VALIDATION_RESPONSE
};


struct ICall {
    ICall(CallAction action, uint64_t messageId): action(action), ocppJmessageId(messageId), ocppJcallId(nullptr) {}
    ICall(CallAction action, const char *callId): action(action), ocppJmessageId(0), ocppJcallId(callId) {}
    ICall(const ICall &) = delete;
    ICall& operator=(const ICall &) = delete;

    virtual ~ICall();

    size_t measureJson() const;
    virtual size_t serializeJson(char *buf, size_t buf_len) const = 0;

    CallAction action;
    uint64_t ocppJmessageId;
    const char *ocppJcallId;
};

struct ResetView {
    JsonObject _obj;

    ResetType type() {

        return (ResetType)_obj["type"].as<size_t>();
    }

    Option<int32_t> evseId() {
        if (!_obj.containsKey("evseId"))
                return {};

        return _obj["evseId"].as<int32_t>();
    }

};

struct TriggerMessageEvseEntriesView {
    JsonObject _obj;

    int32_t id() {

        return _obj["id"].as<int32_t>();
    }

    Option<int32_t> connectorId() {
        if (!_obj.containsKey("connectorId"))
                return {};

        return _obj["connectorId"].as<int32_t>();
    }

};

struct TriggerMessageView {
    JsonObject _obj;

    Option<TriggerMessageEvseEntriesView> evse() {
        if (!_obj.containsKey("evse"))
                return {};

        return Option<TriggerMessageEvseEntriesView>{TriggerMessageEvseEntriesView{_obj["evse"].as<JsonObject>()}};
    }

    TriggerMessageRequestedMessage requestedMessage() {

        return (TriggerMessageRequestedMessage)_obj["requestedMessage"].as<size_t>();
    }

    Option<const char *> customTrigger() {
        if (!_obj.containsKey("customTrigger"))
                return {};

        return _obj["customTrigger"].as<const char *>();
    }

};

struct GetBaseReportView {
    JsonObject _obj;

    int32_t requestId() {

        return _obj["requestId"].as<int32_t>();
    }

    GetBaseReportReportBase reportBase() {

        return (GetBaseReportReportBase)_obj["reportBase"].as<size_t>();
    }

};

struct SetVariablesSetVariableDataEntryEntriesVariableEntriesView {
    JsonObject _obj;

    const char * name() {

        return _obj["name"].as<const char *>();
    }

    Option<const char *> instance() {
        if (!_obj.containsKey("instance"))
                return {};

        return _obj["instance"].as<const char *>();
    }

};

struct SetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesView {
    JsonObject _obj;

    int32_t id() {

        return _obj["id"].as<int32_t>();
    }

    Option<int32_t> connectorId() {
        if (!_obj.containsKey("connectorId"))
                return {};

        return _obj["connectorId"].as<int32_t>();
    }

};

struct SetVariablesSetVariableDataEntryEntriesComponentEntriesView {
    JsonObject _obj;

    Option<SetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesView> evse() {
        if (!_obj.containsKey("evse"))
                return {};

        return Option<SetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesView>{SetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesView{_obj["evse"].as<JsonObject>()}};
    }

    const char * name() {

        return _obj["name"].as<const char *>();
    }

    Option<const char *> instance() {
        if (!_obj.containsKey("instance"))
                return {};

        return _obj["instance"].as<const char *>();
    }

};

struct SetVariablesSetVariableDataEntryEntriesView {
    JsonObject _obj;

    Option<AttributeEnumType> attributeType() {
        if (!_obj.containsKey("attributeType"))
                return {};

        return Option<AttributeEnumType>{(AttributeEnumType)_obj["attributeType"].as<size_t>()};
    }

    const char * attributeValue() {

        return _obj["attributeValue"].as<const char *>();
    }

    SetVariablesSetVariableDataEntryEntriesComponentEntriesView component() {

        return SetVariablesSetVariableDataEntryEntriesComponentEntriesView{_obj["component"].as<JsonObject>()};
    }

    SetVariablesSetVariableDataEntryEntriesVariableEntriesView variable() {

        return SetVariablesSetVariableDataEntryEntriesVariableEntriesView{_obj["variable"].as<JsonObject>()};
    }

};

struct SetVariablesView {
    JsonObject _obj;

    size_t setVariableData_count() {

        return _obj["setVariableData"].size();
    }

    SetVariablesSetVariableDataEntryEntriesView setVariableData(size_t i) {

        return SetVariablesSetVariableDataEntryEntriesView{_obj["setVariableData"][i]};
    }

};

struct GetVariablesGetVariableDataEntryEntriesVariableEntriesView {
    JsonObject _obj;

    const char * name() {

        return _obj["name"].as<const char *>();
    }

    Option<const char *> instance() {
        if (!_obj.containsKey("instance"))
                return {};

        return _obj["instance"].as<const char *>();
    }

};

struct GetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesView {
    JsonObject _obj;

    int32_t id() {

        return _obj["id"].as<int32_t>();
    }

    Option<int32_t> connectorId() {
        if (!_obj.containsKey("connectorId"))
                return {};

        return _obj["connectorId"].as<int32_t>();
    }

};

struct GetVariablesGetVariableDataEntryEntriesComponentEntriesView {
    JsonObject _obj;

    Option<GetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesView> evse() {
        if (!_obj.containsKey("evse"))
                return {};

        return Option<GetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesView>{GetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesView{_obj["evse"].as<JsonObject>()}};
    }

    const char * name() {

        return _obj["name"].as<const char *>();
    }

    Option<const char *> instance() {
        if (!_obj.containsKey("instance"))
                return {};

        return _obj["instance"].as<const char *>();
    }

};

struct GetVariablesGetVariableDataEntryEntriesView {
    JsonObject _obj;

    Option<AttributeEnumType> attributeType() {
        if (!_obj.containsKey("attributeType"))
                return {};

        return Option<AttributeEnumType>{(AttributeEnumType)_obj["attributeType"].as<size_t>()};
    }

    GetVariablesGetVariableDataEntryEntriesComponentEntriesView component() {

        return GetVariablesGetVariableDataEntryEntriesComponentEntriesView{_obj["component"].as<JsonObject>()};
    }

    GetVariablesGetVariableDataEntryEntriesVariableEntriesView variable() {

        return GetVariablesGetVariableDataEntryEntriesVariableEntriesView{_obj["variable"].as<JsonObject>()};
    }

};

struct GetVariablesView {
    JsonObject _obj;

    size_t getVariableData_count() {

        return _obj["getVariableData"].size();
    }

    GetVariablesGetVariableDataEntryEntriesView getVariableData(size_t i) {

        return GetVariablesGetVariableDataEntryEntriesView{_obj["getVariableData"][i]};
    }

};

struct StatusNotificationResponseView {
    JsonObject _obj;

};

struct HeartbeatResponseView {
    JsonObject _obj;

    time_t currentTime() {

        return _obj["currentTime"].as<time_t>();
    }

};

struct BootNotificationResponseStatusInfoEntriesView {
    JsonObject _obj;

    const char * reasonCode() {

        return _obj["reasonCode"].as<const char *>();
    }

    Option<const char *> additionalInfo() {
        if (!_obj.containsKey("additionalInfo"))
                return {};

        return _obj["additionalInfo"].as<const char *>();
    }

};

struct BootNotificationResponseView {
    JsonObject _obj;

    time_t currentTime() {

        return _obj["currentTime"].as<time_t>();
    }

    int32_t interval() {

        return _obj["interval"].as<int32_t>();
    }

    BootNotificationResponseStatus status() {

        return (BootNotificationResponseStatus)_obj["status"].as<size_t>();
    }

    Option<BootNotificationResponseStatusInfoEntriesView> statusInfo() {
        if (!_obj.containsKey("statusInfo"))
                return {};

        return Option<BootNotificationResponseStatusInfoEntriesView>{BootNotificationResponseStatusInfoEntriesView{_obj["statusInfo"].as<JsonObject>()}};
    }

};

struct SetVariablesResponseSetVariableResultComponentEvse {
    int32_t id;
    int32_t connectorId = OCPP_INTEGER_NOT_PASSED;

    void serializeInto(TFJsonSerializer &json);
};

struct GetVariablesResponseGetVariableResultComponentEvse {
    int32_t id;
    int32_t connectorId = OCPP_INTEGER_NOT_PASSED;

    void serializeInto(TFJsonSerializer &json);
};

struct SetVariablesResponseSetVariableResultVariable {
    const char *name;
    const char *instance = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct SetVariablesResponseSetVariableResultComponent {
    SetVariablesResponseSetVariableResultComponentEvse *evse = nullptr;
    const char *name;
    const char *instance = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct SetVariablesResponseSetVariableResultAttributeStatusInfo {
    const char *reasonCode;
    const char *additionalInfo = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct GetVariablesResponseGetVariableResultVariable {
    const char *name;
    const char *instance = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct GetVariablesResponseGetVariableResultComponent {
    GetVariablesResponseGetVariableResultComponentEvse *evse = nullptr;
    const char *name;
    const char *instance = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct GetVariablesResponseGetVariableResultAttributeStatusInfo {
    const char *reasonCode;
    const char *additionalInfo = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct BootNotificationChargingStationModem {
    const char *iccid = nullptr;
    const char *imsi = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct ResetResponseStatusInfo {
    const char *reasonCode;
    const char *additionalInfo = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct TriggerMessageResponseStatusInfo {
    const char *reasonCode;
    const char *additionalInfo = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct GetBaseReportResponseStatusInfo {
    const char *reasonCode;
    const char *additionalInfo = nullptr;

    void serializeInto(TFJsonSerializer &json);
};

struct SetVariablesResponseSetVariableResult {
    GetVariableResultAttributeEnumType attributeType = GetVariableResultAttributeEnumType::NONE;
    SetVariablesResponseSetVariableResultAttributeStatus attributeStatus;
    SetVariablesResponseSetVariableResultAttributeStatusInfo *attributeStatusInfo = nullptr;
    SetVariablesResponseSetVariableResultComponent *component;
    SetVariablesResponseSetVariableResultVariable *variable;

    void serializeInto(TFJsonSerializer &json);
};

struct GetVariablesResponseGetVariableResult {
    GetVariablesResponseGetVariableResultAttributeStatus attributeStatus;
    GetVariablesResponseGetVariableResultAttributeStatusInfo *attributeStatusInfo = nullptr;
    GetVariableResultAttributeEnumType attributeType = GetVariableResultAttributeEnumType::NONE;
    const char *attributeValue = nullptr;
    GetVariablesResponseGetVariableResultComponent *component;
    GetVariablesResponseGetVariableResultVariable *variable;

    void serializeInto(TFJsonSerializer &json);
};

struct BootNotificationChargingStation {
    const char *serialNumber = nullptr;
    const char *model;
    BootNotificationChargingStationModem *modem = nullptr;
    const char *vendorName;
    const char *firmwareVersion = nullptr;

    void serializeInto(TFJsonSerializer &json);
};


CallResponse callHandler(const char *uid, const char *action_string, JsonObject obj, ChargePoint21 *cp);

struct BootNotification final : public ICall {
    BootNotificationChargingStation *chargingStation;
    BootNotificationReason reason;

    BootNotification(BootNotificationChargingStation *chargingStation,
        BootNotificationReason reason);
    BootNotification(const BootNotification&) = delete;
    BootNotification &operator=(const BootNotification&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct Heartbeat final : public ICall {

    Heartbeat();
    Heartbeat(const Heartbeat&) = delete;
    Heartbeat &operator=(const Heartbeat&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct StatusNotification final : public ICall {
    time_t timestamp;
    StatusNotificationConnectorStatus connectorStatus;
    int32_t evseId;
    int32_t connectorId;

    StatusNotification(time_t timestamp,
        StatusNotificationConnectorStatus connectorStatus,
        int32_t evseId,
        int32_t connectorId);
    StatusNotification(const StatusNotification&) = delete;
    StatusNotification &operator=(const StatusNotification&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct GetVariablesResponse final : public ICall {
    GetVariablesResponseGetVariableResult *getVariableResult; size_t getVariableResult_length;

    GetVariablesResponse(const char *call_id,
        GetVariablesResponseGetVariableResult *getVariableResult, size_t getVariableResult_length);
    GetVariablesResponse(const GetVariablesResponse&) = delete;
    GetVariablesResponse &operator=(const GetVariablesResponse&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct SetVariablesResponse final : public ICall {
    SetVariablesResponseSetVariableResult *setVariableResult; size_t setVariableResult_length;

    SetVariablesResponse(const char *call_id,
        SetVariablesResponseSetVariableResult *setVariableResult, size_t setVariableResult_length);
    SetVariablesResponse(const SetVariablesResponse&) = delete;
    SetVariablesResponse &operator=(const SetVariablesResponse&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct GetBaseReportResponse final : public ICall {
    GetBaseReportResponseStatus status;
    GetBaseReportResponseStatusInfo *statusInfo;

    GetBaseReportResponse(const char *call_id,
        GetBaseReportResponseStatus status,
        GetBaseReportResponseStatusInfo *statusInfo = nullptr);
    GetBaseReportResponse(const GetBaseReportResponse&) = delete;
    GetBaseReportResponse &operator=(const GetBaseReportResponse&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct TriggerMessageResponse final : public ICall {
    TriggerMessageResponseStatus status;
    TriggerMessageResponseStatusInfo *statusInfo;

    TriggerMessageResponse(const char *call_id,
        TriggerMessageResponseStatus status,
        TriggerMessageResponseStatusInfo *statusInfo = nullptr);
    TriggerMessageResponse(const TriggerMessageResponse&) = delete;
    TriggerMessageResponse &operator=(const TriggerMessageResponse&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

struct ResetResponse final : public ICall {
    ResetResponseStatus status;
    ResetResponseStatusInfo *statusInfo;

    ResetResponse(const char *call_id,
        ResetResponseStatus status,
        ResetResponseStatusInfo *statusInfo = nullptr);
    ResetResponse(const ResetResponse&) = delete;
    ResetResponse &operator=(const ResetResponse&) = delete;

    size_t serializeJson(char *buf, size_t buf_len) const override;
};

CallResponse parseBootNotificationResponse(JsonObject obj);

CallResponse parseHeartbeatResponse(JsonObject obj);

CallResponse parseStatusNotificationResponse(JsonObject obj);

CallResponse parseGetVariables(JsonObject obj);

CallResponse parseSetVariables(JsonObject obj);

CallResponse parseGetBaseReport(JsonObject obj);

CallResponse parseTriggerMessage(JsonObject obj);

CallResponse parseReset(JsonObject obj);

CallResponse callResultHandler(int32_t connectorId, CallAction resultTo, JsonObject obj, ChargePoint21 *cp);


} // namespace Ocpp21
