// THIS FILE IS AUTO-GENERATED BY generator21.py. DO NOT EDIT.

#include "Messages21.h"

#include "ChargePoint21.h"
#include "Types21.h"
#include <common/Tools.h>

extern "C" {
#include "lib/libiso8601/iso8601.h"
}

#include "TFJson.h"

namespace Ocpp21 {

static bool iso_string_to_unix_timestamp(const char *iso_string, time_t *t) {
    iso8601_time time;
    if (iso8601_parse(iso_string, &time) != 0) {
        return false;
    }
    iso8601_to_time_t(&time, t);
    return true;
}

static void unix_timestamp_to_iso_string(time_t timestamp, TFJsonSerializer &json, const char *key) {
    char buf[OCPP_ISO_8601_MAX_LEN] = {0};
    tm t;
    gmtime_r(&timestamp, &t);

    strftime(buf, ARRAY_SIZE(buf), "%FT%TZ", &t);

    json.addMemberString(key, buf);
}

ICall::~ICall() {}

size_t ICall::measureJson() const {
    return this->serializeJson(nullptr, 0);
}

uint64_t next_call_id = 0;

const char * const BootNotificationReasonStrings[] = {
    "ApplicationReset",
    "FirmwareUpdate",
    "LocalReset",
    "PowerUp",
    "RemoteReset",
    "ScheduledReset",
    "Triggered",
    "Unknown",
    "Watchdog"
};

const char * const StatusNotificationConnectorStatusStrings[] = {
    "Available",
    "Occupied",
    "Reserved",
    "Unavailable",
    "Faulted"
};

const char * const GetBaseReportResponseStatusStrings[] = {
    "Accepted",
    "Rejected",
    "NotSupported",
    "EmptyResultSet"
};

const char * const TriggerMessageResponseStatusStrings[] = {
    "Accepted",
    "Rejected",
    "NotImplemented"
};

const char * const ResetResponseStatusStrings[] = {
    "Accepted",
    "Rejected",
    "Scheduled"
};

const char * const BootNotificationResponseStatusStrings[] = {
    "Accepted",
    "Pending",
    "Rejected"
};

const char * const AttributeEnumTypeStrings[] = {
    "Actual",
    "Target",
    "MinSet",
    "MaxSet"
};

const char * const GetBaseReportReportBaseStrings[] = {
    "ConfigurationInventory",
    "FullInventory",
    "SummaryInventory"
};

const char * const TriggerMessageRequestedMessageStrings[] = {
    "BootNotification",
    "LogStatusNotification",
    "FirmwareStatusNotification",
    "Heartbeat",
    "MeterValues",
    "SignChargingStationCertificate",
    "SignV2GCertificate",
    "SignV2G20Certificate",
    "StatusNotification",
    "TransactionEvent",
    "SignCombinedCertificate",
    "PublishFirmwareStatusNotification",
    "CustomTrigger"
};

const char * const ResetTypeStrings[] = {
    "Immediate",
    "OnIdle",
    "ImmediateAndResume"
};

const char * const GetVariablesResponseGetVariableResultAttributeStatusStrings[] = {
    "Accepted",
    "Rejected",
    "UnknownComponent",
    "UnknownVariable",
    "NotSupportedAttributeType"
};

const char * const GetVariableResultAttributeEnumTypeStrings[] = {
    "Actual",
    "Target",
    "MinSet",
    "MaxSet"
};

const char * const SetVariablesResponseSetVariableResultAttributeStatusStrings[] = {
    "Accepted",
    "Rejected",
    "UnknownComponent",
    "UnknownVariable",
    "NotSupportedAttributeType",
    "RebootRequired"
};

const char * const CallActionStrings[] = {
    "AFRRSignal",
    "AFRRSignalResponse",
    "AdjustPeriodicEventStream",
    "AdjustPeriodicEventStreamResponse",
    "Authorize",
    "AuthorizeResponse",
    "BatterySwap",
    "BatterySwapResponse",
    "BootNotification",
    "BootNotificationResponse",
    "CancelReservation",
    "CancelReservationResponse",
    "CertificateSigned",
    "CertificateSignedResponse",
    "ChangeAvailability",
    "ChangeAvailabilityResponse",
    "ChangeTransactionTariff",
    "ChangeTransactionTariffResponse",
    "ClearCache",
    "ClearCacheResponse",
    "ClearChargingProfile",
    "ClearChargingProfileResponse",
    "ClearDERControl",
    "ClearDERControlResponse",
    "ClearDisplayMessage",
    "ClearDisplayMessageResponse",
    "ClearTariffs",
    "ClearTariffsResponse",
    "ClearVariableMonitoring",
    "ClearVariableMonitoringResponse",
    "ClearedChargingLimit",
    "ClearedChargingLimitResponse",
    "ClosePeriodicEventStream",
    "ClosePeriodicEventStreamResponse",
    "CostUpdated",
    "CostUpdatedResponse",
    "CustomerInformation",
    "CustomerInformationResponse",
    "DataTransfer",
    "DataTransferResponse",
    "DeleteCertificate",
    "DeleteCertificateResponse",
    "FirmwareStatusNotification",
    "FirmwareStatusNotificationResponse",
    "Get15118EVCertificate",
    "Get15118EVCertificateResponse",
    "GetBaseReport",
    "GetBaseReportResponse",
    "GetCertificateChainStatus",
    "GetCertificateChainStatusResponse",
    "GetCertificateStatus",
    "GetCertificateStatusResponse",
    "GetChargingProfiles",
    "GetChargingProfilesResponse",
    "GetCompositeSchedule",
    "GetCompositeScheduleResponse",
    "GetDERControl",
    "GetDERControlResponse",
    "GetDisplayMessages",
    "GetDisplayMessagesResponse",
    "GetInstalledCertificateIds",
    "GetInstalledCertificateIdsResponse",
    "GetLocalListVersion",
    "GetLocalListVersionResponse",
    "GetLog",
    "GetLogResponse",
    "GetMonitoringReport",
    "GetMonitoringReportResponse",
    "GetPeriodicEventStream",
    "GetPeriodicEventStreamResponse",
    "GetReport",
    "GetReportResponse",
    "GetTariffs",
    "GetTariffsResponse",
    "GetTransactionStatus",
    "GetTransactionStatusResponse",
    "GetVariables",
    "GetVariablesResponse",
    "Heartbeat",
    "HeartbeatResponse",
    "InstallCertificate",
    "InstallCertificateResponse",
    "LogStatusNotification",
    "LogStatusNotificationResponse",
    "MeterValues",
    "MeterValuesResponse",
    "NotifyAllowedEnergyTransfer",
    "NotifyAllowedEnergyTransferResponse",
    "NotifyChargingLimit",
    "NotifyChargingLimitResponse",
    "NotifyCustomerInformation",
    "NotifyCustomerInformationResponse",
    "NotifyDERAlarm",
    "NotifyDERAlarmResponse",
    "NotifyDERStartStop",
    "NotifyDERStartStopResponse",
    "NotifyDisplayMessages",
    "NotifyDisplayMessagesResponse",
    "NotifyEVChargingNeeds",
    "NotifyEVChargingNeedsResponse",
    "NotifyEVChargingSchedule",
    "NotifyEVChargingScheduleResponse",
    "NotifyEvent",
    "NotifyEventResponse",
    "NotifyMonitoringReport",
    "NotifyMonitoringReportResponse",
    "NotifyPeriodicEventStream",
    "NotifyPriorityCharging",
    "NotifyPriorityChargingResponse",
    "NotifyReport",
    "NotifyReportResponse",
    "NotifySettlement",
    "NotifySettlementResponse",
    "NotifyWebPaymentStarted",
    "NotifyWebPaymentStartedResponse",
    "OpenPeriodicEventStream",
    "OpenPeriodicEventStreamResponse",
    "PublishFirmware",
    "PublishFirmwareResponse",
    "PublishFirmwareStatusNotification",
    "PublishFirmwareStatusNotificationResponse",
    "PullDynamicScheduleUpdate",
    "PullDynamicScheduleUpdateResponse",
    "ReportChargingProfiles",
    "ReportChargingProfilesResponse",
    "ReportDERControl",
    "ReportDERControlResponse",
    "RequestBatterySwap",
    "RequestBatterySwapResponse",
    "RequestStartTransaction",
    "RequestStartTransactionResponse",
    "RequestStopTransaction",
    "RequestStopTransactionResponse",
    "ReservationStatusUpdate",
    "ReservationStatusUpdateResponse",
    "ReserveNow",
    "ReserveNowResponse",
    "Reset",
    "ResetResponse",
    "SecurityEventNotification",
    "SecurityEventNotificationResponse",
    "SendLocalList",
    "SendLocalListResponse",
    "SetChargingProfile",
    "SetChargingProfileResponse",
    "SetDERControl",
    "SetDERControlResponse",
    "SetDefaultTariff",
    "SetDefaultTariffResponse",
    "SetDisplayMessage",
    "SetDisplayMessageResponse",
    "SetMonitoringBase",
    "SetMonitoringBaseResponse",
    "SetMonitoringLevel",
    "SetMonitoringLevelResponse",
    "SetNetworkProfile",
    "SetNetworkProfileResponse",
    "SetVariableMonitoring",
    "SetVariableMonitoringResponse",
    "SetVariables",
    "SetVariablesResponse",
    "SignCertificate",
    "SignCertificateResponse",
    "StatusNotification",
    "StatusNotificationResponse",
    "TransactionEvent",
    "TransactionEventResponse",
    "TriggerMessage",
    "TriggerMessageResponse",
    "UnlockConnector",
    "UnlockConnectorResponse",
    "UnpublishFirmware",
    "UnpublishFirmwareResponse",
    "UpdateDynamicSchedule",
    "UpdateDynamicScheduleResponse",
    "UpdateFirmware",
    "UpdateFirmwareResponse",
    "UsePriorityCharging",
    "UsePriorityChargingResponse",
    "VatNumberValidation",
    "VatNumberValidationResponse"
};


void BootNotificationChargingStation::serializeInto(TFJsonSerializer &json) {
        if (serialNumber != nullptr) json.addMemberString("serialNumber", serialNumber);
        if (model != nullptr) json.addMemberString("model", model);
        if (modem != nullptr) { json.addMemberObject("modem"); modem->serializeInto(json); json.endObject(); }
        if (vendorName != nullptr) json.addMemberString("vendorName", vendorName);
        if (firmwareVersion != nullptr) json.addMemberString("firmwareVersion", firmwareVersion);
    }

void GetVariablesResponseGetVariableResult::serializeInto(TFJsonSerializer &json) {
        if (attributeStatus != GetVariablesResponseGetVariableResultAttributeStatus::NONE) json.addMemberString("attributeStatus", GetVariablesResponseGetVariableResultAttributeStatusStrings[(size_t)attributeStatus]);
        if (attributeStatusInfo != nullptr) { json.addMemberObject("attributeStatusInfo"); attributeStatusInfo->serializeInto(json); json.endObject(); }
        if (attributeType != GetVariableResultAttributeEnumType::NONE) json.addMemberString("attributeType", GetVariableResultAttributeEnumTypeStrings[(size_t)attributeType]);
        if (attributeValue != nullptr) json.addMemberString("attributeValue", attributeValue);
        if (component != nullptr) { json.addMemberObject("component"); component->serializeInto(json); json.endObject(); }
        if (variable != nullptr) { json.addMemberObject("variable"); variable->serializeInto(json); json.endObject(); }
    }

void SetVariablesResponseSetVariableResult::serializeInto(TFJsonSerializer &json) {
        if (attributeType != GetVariableResultAttributeEnumType::NONE) json.addMemberString("attributeType", GetVariableResultAttributeEnumTypeStrings[(size_t)attributeType]);
        if (attributeStatus != SetVariablesResponseSetVariableResultAttributeStatus::NONE) json.addMemberString("attributeStatus", SetVariablesResponseSetVariableResultAttributeStatusStrings[(size_t)attributeStatus]);
        if (attributeStatusInfo != nullptr) { json.addMemberObject("attributeStatusInfo"); attributeStatusInfo->serializeInto(json); json.endObject(); }
        if (component != nullptr) { json.addMemberObject("component"); component->serializeInto(json); json.endObject(); }
        if (variable != nullptr) { json.addMemberObject("variable"); variable->serializeInto(json); json.endObject(); }
    }

void GetBaseReportResponseStatusInfo::serializeInto(TFJsonSerializer &json) {
        if (reasonCode != nullptr) json.addMemberString("reasonCode", reasonCode);
        if (additionalInfo != nullptr) json.addMemberString("additionalInfo", additionalInfo);
    }

void TriggerMessageResponseStatusInfo::serializeInto(TFJsonSerializer &json) {
        if (reasonCode != nullptr) json.addMemberString("reasonCode", reasonCode);
        if (additionalInfo != nullptr) json.addMemberString("additionalInfo", additionalInfo);
    }

void ResetResponseStatusInfo::serializeInto(TFJsonSerializer &json) {
        if (reasonCode != nullptr) json.addMemberString("reasonCode", reasonCode);
        if (additionalInfo != nullptr) json.addMemberString("additionalInfo", additionalInfo);
    }

void BootNotificationChargingStationModem::serializeInto(TFJsonSerializer &json) {
        if (iccid != nullptr) json.addMemberString("iccid", iccid);
        if (imsi != nullptr) json.addMemberString("imsi", imsi);
    }

void GetVariablesResponseGetVariableResultAttributeStatusInfo::serializeInto(TFJsonSerializer &json) {
        if (reasonCode != nullptr) json.addMemberString("reasonCode", reasonCode);
        if (additionalInfo != nullptr) json.addMemberString("additionalInfo", additionalInfo);
    }

void GetVariablesResponseGetVariableResultComponent::serializeInto(TFJsonSerializer &json) {
        if (evse != nullptr) { json.addMemberObject("evse"); evse->serializeInto(json); json.endObject(); }
        if (name != nullptr) json.addMemberString("name", name);
        if (instance != nullptr) json.addMemberString("instance", instance);
    }

void GetVariablesResponseGetVariableResultVariable::serializeInto(TFJsonSerializer &json) {
        if (name != nullptr) json.addMemberString("name", name);
        if (instance != nullptr) json.addMemberString("instance", instance);
    }

void SetVariablesResponseSetVariableResultAttributeStatusInfo::serializeInto(TFJsonSerializer &json) {
        if (reasonCode != nullptr) json.addMemberString("reasonCode", reasonCode);
        if (additionalInfo != nullptr) json.addMemberString("additionalInfo", additionalInfo);
    }

void SetVariablesResponseSetVariableResultComponent::serializeInto(TFJsonSerializer &json) {
        if (evse != nullptr) { json.addMemberObject("evse"); evse->serializeInto(json); json.endObject(); }
        if (name != nullptr) json.addMemberString("name", name);
        if (instance != nullptr) json.addMemberString("instance", instance);
    }

void SetVariablesResponseSetVariableResultVariable::serializeInto(TFJsonSerializer &json) {
        if (name != nullptr) json.addMemberString("name", name);
        if (instance != nullptr) json.addMemberString("instance", instance);
    }

void GetVariablesResponseGetVariableResultComponentEvse::serializeInto(TFJsonSerializer &json) {
        if (id != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("id", id);
        if (connectorId != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("connectorId", connectorId);
    }

void SetVariablesResponseSetVariableResultComponentEvse::serializeInto(TFJsonSerializer &json) {
        if (id != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("id", id);
        if (connectorId != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("connectorId", connectorId);
    }



BootNotification::BootNotification(BootNotificationChargingStation *chargingStation,
        BootNotificationReason reason) :
    ICall(CallAction::BOOT_NOTIFICATION, next_call_id++),
    chargingStation(chargingStation),
    reason(reason)
{}

size_t BootNotification::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALL);
        json.addNumber(this->ocppJmessageId, true);
        json.addString(CallActionStrings[(size_t)this->action]);
        json.addObject();
            if (chargingStation != nullptr) { json.addMemberObject("chargingStation"); chargingStation->serializeInto(json); json.endObject(); }
            if (reason != BootNotificationReason::NONE) json.addMemberString("reason", BootNotificationReasonStrings[(size_t)reason]);
        json.endObject();
    json.endArray();

    return json.end();
}

Heartbeat::Heartbeat() :
    ICall(CallAction::HEARTBEAT, next_call_id++)
{}

size_t Heartbeat::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALL);
        json.addNumber(this->ocppJmessageId, true);
        json.addString(CallActionStrings[(size_t)this->action]);
        json.addObject();

        json.endObject();
    json.endArray();

    return json.end();
}

StatusNotification::StatusNotification(time_t timestamp,
        StatusNotificationConnectorStatus connectorStatus,
        int32_t evseId,
        int32_t connectorId) :
    ICall(CallAction::STATUS_NOTIFICATION, next_call_id++),
    timestamp(timestamp),
    connectorStatus(connectorStatus),
    evseId(evseId),
    connectorId(connectorId)
{}

size_t StatusNotification::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALL);
        json.addNumber(this->ocppJmessageId, true);
        json.addString(CallActionStrings[(size_t)this->action]);
        json.addObject();
            if (timestamp != OCPP_DATETIME_NOT_PASSED) unix_timestamp_to_iso_string(timestamp, json, "timestamp");
            if (connectorStatus != StatusNotificationConnectorStatus::NONE) json.addMemberString("connectorStatus", StatusNotificationConnectorStatusStrings[(size_t)connectorStatus]);
            if (evseId != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("evseId", evseId);
            if (connectorId != OCPP_INTEGER_NOT_PASSED) json.addMemberNumber("connectorId", connectorId);
        json.endObject();
    json.endArray();

    return json.end();
}

GetVariablesResponse::GetVariablesResponse(const char *call_id,
        GetVariablesResponseGetVariableResult *getVariableResult, size_t getVariableResult_length) :
    ICall(CallAction::GET_VARIABLES_RESPONSE, call_id),
    getVariableResult(getVariableResult),
    getVariableResult_length(getVariableResult_length)
{}

size_t GetVariablesResponse::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALLRESULT);
        json.addString(this->ocppJcallId);

        json.addObject();
            if (getVariableResult != nullptr) { json.addMemberArray("getVariableResult"); for(size_t i = 0; i < getVariableResult_length; ++i) { json.addObject(); getVariableResult[i].serializeInto(json); json.endObject(); } json.endArray(); }
        json.endObject();
    json.endArray();

    return json.end();
}

SetVariablesResponse::SetVariablesResponse(const char *call_id,
        SetVariablesResponseSetVariableResult *setVariableResult, size_t setVariableResult_length) :
    ICall(CallAction::SET_VARIABLES_RESPONSE, call_id),
    setVariableResult(setVariableResult),
    setVariableResult_length(setVariableResult_length)
{}

size_t SetVariablesResponse::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALLRESULT);
        json.addString(this->ocppJcallId);

        json.addObject();
            if (setVariableResult != nullptr) { json.addMemberArray("setVariableResult"); for(size_t i = 0; i < setVariableResult_length; ++i) { json.addObject(); setVariableResult[i].serializeInto(json); json.endObject(); } json.endArray(); }
        json.endObject();
    json.endArray();

    return json.end();
}

GetBaseReportResponse::GetBaseReportResponse(const char *call_id,
        GetBaseReportResponseStatus status,
        GetBaseReportResponseStatusInfo *statusInfo) :
    ICall(CallAction::GET_BASE_REPORT_RESPONSE, call_id),
    status(status),
    statusInfo(statusInfo)
{}

size_t GetBaseReportResponse::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALLRESULT);
        json.addString(this->ocppJcallId);

        json.addObject();
            if (status != GetBaseReportResponseStatus::NONE) json.addMemberString("status", GetBaseReportResponseStatusStrings[(size_t)status]);
            if (statusInfo != nullptr) { json.addMemberObject("statusInfo"); statusInfo->serializeInto(json); json.endObject(); }
        json.endObject();
    json.endArray();

    return json.end();
}

TriggerMessageResponse::TriggerMessageResponse(const char *call_id,
        TriggerMessageResponseStatus status,
        TriggerMessageResponseStatusInfo *statusInfo) :
    ICall(CallAction::TRIGGER_MESSAGE_RESPONSE, call_id),
    status(status),
    statusInfo(statusInfo)
{}

size_t TriggerMessageResponse::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALLRESULT);
        json.addString(this->ocppJcallId);

        json.addObject();
            if (status != TriggerMessageResponseStatus::NONE) json.addMemberString("status", TriggerMessageResponseStatusStrings[(size_t)status]);
            if (statusInfo != nullptr) { json.addMemberObject("statusInfo"); statusInfo->serializeInto(json); json.endObject(); }
        json.endObject();
    json.endArray();

    return json.end();
}

ResetResponse::ResetResponse(const char *call_id,
        ResetResponseStatus status,
        ResetResponseStatusInfo *statusInfo) :
    ICall(CallAction::RESET_RESPONSE, call_id),
    status(status),
    statusInfo(statusInfo)
{}

size_t ResetResponse::serializeJson(char *buf, size_t buf_len) const {
    TFJsonSerializer json{buf, buf_len};
    json.addArray();
        json.addNumber((int32_t)OcppRpcMessageType::CALLRESULT);
        json.addString(this->ocppJcallId);

        json.addObject();
            if (status != ResetResponseStatus::NONE) json.addMemberString("status", ResetResponseStatusStrings[(size_t)status]);
            if (statusInfo != nullptr) { json.addMemberObject("statusInfo"); statusInfo->serializeInto(json); json.endObject(); }
        json.endObject();
    json.endArray();

    return json.end();
}

static CallResponse parseBootNotificationResponseCurrentTime(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "currentTime: wrong type"};

    {
        time_t result;
        if (!iso_string_to_unix_timestamp(var.as<const char *>(), &result))
            return CallResponse{CallErrorCode::TypeConstraintViolation, "currentTime: failed to parse as ISO 8601 date-time string"};

        var.set(result);
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseBootNotificationResponseInterval(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "interval: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseBootNotificationResponseStatus(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "status: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(BootNotificationResponseStatusStrings); ++i) {
            if (strcmp(var.as<const char *>(), BootNotificationResponseStatusStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "status: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseBootNotificationResponseStatusInfoEntriesReasonCode(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "reasonCode: wrong type"};

    if (strlen(var.as<const char *>()) > 20)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "reasonCode: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseBootNotificationResponseStatusInfoEntriesAdditionalInfo(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "additionalInfo: wrong type"};

    if (strlen(var.as<const char *>()) > 1024)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "additionalInfo: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseBootNotificationResponseStatusInfoEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("reasonCode"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "reasonCode: required, but missing"};

    {
        CallResponse inner_result = parseBootNotificationResponseStatusInfoEntriesReasonCode(obj["reasonCode"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("additionalInfo")) {
    {
        CallResponse inner_result = parseBootNotificationResponseStatusInfoEntriesAdditionalInfo(obj["additionalInfo"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "BootNotificationResponseStatusInfoEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseBootNotificationResponseStatusInfo(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "statusInfo: wrong type"};

    {
        CallResponse inner_result = parseBootNotificationResponseStatusInfoEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseBootNotificationResponse(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("currentTime"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "currentTime: required, but missing"};

    {
        CallResponse inner_result = parseBootNotificationResponseCurrentTime(obj["currentTime"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("interval"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "interval: required, but missing"};

    {
        CallResponse inner_result = parseBootNotificationResponseInterval(obj["interval"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("status"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "status: required, but missing"};

    {
        CallResponse inner_result = parseBootNotificationResponseStatus(obj["status"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("statusInfo")) {
    {
        CallResponse inner_result = parseBootNotificationResponseStatusInfo(obj["statusInfo"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "BootNotificationResponse: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseHeartbeatResponseCurrentTime(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "currentTime: wrong type"};

    {
        time_t result;
        if (!iso_string_to_unix_timestamp(var.as<const char *>(), &result))
            return CallResponse{CallErrorCode::TypeConstraintViolation, "currentTime: failed to parse as ISO 8601 date-time string"};

        var.set(result);
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseHeartbeatResponse(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("currentTime"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "currentTime: required, but missing"};

    {
        CallResponse inner_result = parseHeartbeatResponseCurrentTime(obj["currentTime"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "HeartbeatResponse: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

CallResponse parseStatusNotificationResponse(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "StatusNotificationResponse: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGAttributeEnumType(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "attributeType: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(AttributeEnumTypeStrings); ++i) {
            if (strcmp(var.as<const char *>(), AttributeEnumTypeStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "attributeType: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "id: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesConnectorId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "connectorId: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("id"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "id: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesId(obj["id"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("connectorId")) {
    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntriesConnectorId(obj["connectorId"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvse(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "evse: wrong type"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvseEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesName(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "name: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "name: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntriesInstance(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "instance: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "instance: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponentEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("evse")) {
    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesEvse(obj["evse"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }

    if (!obj.containsKey("name"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "name: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesName(obj["name"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("instance")) {
    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntriesInstance(obj["instance"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetVariablesGetVariableDataEntryEntriesComponentEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesComponent(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "component: wrong type"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponentEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesVariableEntriesName(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "name: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "name: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetVariablesGetVariableDataEntryEntriesVariableEntriesInstance(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "instance: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "instance: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesVariableEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("name"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "name: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesVariableEntriesName(obj["name"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("instance")) {
    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesVariableEntriesInstance(obj["instance"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetVariablesGetVariableDataEntryEntriesVariableEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntriesVariable(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "variable: wrong type"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesVariableEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntryEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("attributeType")) {
    {
        CallResponse inner_result = parseGetVariablesGAttributeEnumType(obj["attributeType"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }

    if (!obj.containsKey("component"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "component: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesComponent(obj["component"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("variable"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "variable: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntriesVariable(obj["variable"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetVariablesGetVariableDataEntryEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableDataEntry(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "getVariableDataEntry: wrong type"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableDataEntryEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseGetVariablesGetVariableData(JsonVariant var) {

    if (!var.is<JsonArray>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "getVariableData: wrong type"};

    {
        for(size_t i = 0; i < var.as<JsonArray>().size(); ++i) {
            CallResponse inner_result = parseGetVariablesGetVariableDataEntry(var[i]);
            if (inner_result.result != CallErrorCode::OK)
                return inner_result;
        }
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseGetVariables(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("getVariableData"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "getVariableData: required, but missing"};

    {
        CallResponse inner_result = parseGetVariablesGetVariableData(obj["getVariableData"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetVariables: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSAttributeEnumType(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "attributeType: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(AttributeEnumTypeStrings); ++i) {
            if (strcmp(var.as<const char *>(), AttributeEnumTypeStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "attributeType: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesAttributeValue(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "attributeValue: wrong type"};

    if (strlen(var.as<const char *>()) > 2500)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "attributeValue: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "id: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesConnectorId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "connectorId: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("id"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "id: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesId(obj["id"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("connectorId")) {
    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntriesConnectorId(obj["connectorId"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "SetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvse(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "evse: wrong type"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvseEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesName(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "name: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "name: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntriesInstance(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "instance: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "instance: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponentEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("evse")) {
    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesEvse(obj["evse"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }

    if (!obj.containsKey("name"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "name: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesName(obj["name"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("instance")) {
    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntriesInstance(obj["instance"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "SetVariablesSetVariableDataEntryEntriesComponentEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesComponent(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "component: wrong type"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponentEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesVariableEntriesName(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "name: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "name: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseSetVariablesSetVariableDataEntryEntriesVariableEntriesInstance(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "instance: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "instance: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesVariableEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("name"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "name: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesVariableEntriesName(obj["name"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("instance")) {
    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesVariableEntriesInstance(obj["instance"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "SetVariablesSetVariableDataEntryEntriesVariableEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntriesVariable(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "variable: wrong type"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesVariableEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntryEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("attributeType")) {
    {
        CallResponse inner_result = parseSetVariablesSAttributeEnumType(obj["attributeType"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }

    if (!obj.containsKey("attributeValue"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "attributeValue: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesAttributeValue(obj["attributeValue"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("component"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "component: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesComponent(obj["component"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("variable"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "variable: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntriesVariable(obj["variable"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "SetVariablesSetVariableDataEntryEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableDataEntry(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "setVariableDataEntry: wrong type"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableDataEntryEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseSetVariablesSetVariableData(JsonVariant var) {

    if (!var.is<JsonArray>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "setVariableData: wrong type"};

    {
        for(size_t i = 0; i < var.as<JsonArray>().size(); ++i) {
            CallResponse inner_result = parseSetVariablesSetVariableDataEntry(var[i]);
            if (inner_result.result != CallErrorCode::OK)
                return inner_result;
        }
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseSetVariables(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("setVariableData"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "setVariableData: required, but missing"};

    {
        CallResponse inner_result = parseSetVariablesSetVariableData(obj["setVariableData"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "SetVariables: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetBaseReportRequestId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "requestId: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseGetBaseReportReportBase(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "reportBase: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(GetBaseReportReportBaseStrings); ++i) {
            if (strcmp(var.as<const char *>(), GetBaseReportReportBaseStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "reportBase: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseGetBaseReport(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("requestId"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "requestId: required, but missing"};

    {
        CallResponse inner_result = parseGetBaseReportRequestId(obj["requestId"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;

    if (!obj.containsKey("reportBase"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "reportBase: required, but missing"};

    {
        CallResponse inner_result = parseGetBaseReportReportBase(obj["reportBase"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "GetBaseReport: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseTriggerMessageEvseEntriesId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "id: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseTriggerMessageEvseEntriesConnectorId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "connectorId: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseTriggerMessageEvseEntries(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("id"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "id: required, but missing"};

    {
        CallResponse inner_result = parseTriggerMessageEvseEntriesId(obj["id"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("connectorId")) {
    {
        CallResponse inner_result = parseTriggerMessageEvseEntriesConnectorId(obj["connectorId"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "TriggerMessageEvseEntries: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}
static CallResponse parseTriggerMessageEvse(JsonVariant var) {

    if (!var.is<JsonObject>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "evse: wrong type"};

    {
        CallResponse inner_result = parseTriggerMessageEvseEntries(var);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseTriggerMessageRequestedMessage(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "requestedMessage: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(TriggerMessageRequestedMessageStrings); ++i) {
            if (strcmp(var.as<const char *>(), TriggerMessageRequestedMessageStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "requestedMessage: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseTriggerMessageCustomTrigger(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "customTrigger: wrong type"};

    if (strlen(var.as<const char *>()) > 50)
        return CallResponse{CallErrorCode::PropertyConstraintViolation, "customTrigger: string too long"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseTriggerMessage(JsonObject obj) {
    size_t keys_handled = 0;

    if (obj.containsKey("evse")) {
    {
        CallResponse inner_result = parseTriggerMessageEvse(obj["evse"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }

    if (!obj.containsKey("requestedMessage"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "requestedMessage: required, but missing"};

    {
        CallResponse inner_result = parseTriggerMessageRequestedMessage(obj["requestedMessage"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("customTrigger")) {
    {
        CallResponse inner_result = parseTriggerMessageCustomTrigger(obj["customTrigger"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "TriggerMessage: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseResetType(JsonVariant var) {

    if (!var.is<const char *>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "type: wrong type"};

    {
        bool found = false;
        for(size_t i = 0; i < ARRAY_SIZE(ResetTypeStrings); ++i) {
            if (strcmp(var.as<const char *>(), ResetTypeStrings[i]) != 0)
                continue;

            var.set(i);
            found = true;
            break;
        }

        if (!found)
            return CallResponse{CallErrorCode::PropertyConstraintViolation, "type: unknown enum value received"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

static CallResponse parseResetEvseId(JsonVariant var) {

    if (!var.is<int32_t>())
        return CallResponse{CallErrorCode::TypeConstraintViolation, "evseId: wrong type"};

    return CallResponse{CallErrorCode::OK, nullptr};
}
CallResponse parseReset(JsonObject obj) {
    size_t keys_handled = 0;

    if (!obj.containsKey("type"))
        return CallResponse{CallErrorCode::OccurrenceConstraintViolation, "type: required, but missing"};

    {
        CallResponse inner_result = parseResetType(obj["type"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    if (obj.containsKey("evseId")) {
    {
        CallResponse inner_result = parseResetEvseId(obj["evseId"]);
        if (inner_result.result != CallErrorCode::OK)
            return inner_result;
    }
    ++keys_handled;
    }
    if (obj.containsKey("customData")) ++keys_handled;

    if (obj.size() != keys_handled) {
        return CallResponse{CallErrorCode::FormatViolation, "Reset: unknown members passed"};
    }

    return CallResponse{CallErrorCode::OK, nullptr};
}

CallResponse callHandler(const char *uid, const char *action_string, JsonObject obj, ChargePoint21 *cp) {
    size_t action_idx = 0;
    if (!lookup_key(&action_idx, action_string, CallActionStrings, ARRAY_SIZE(CallActionStrings)))
        return CallResponse{CallErrorCode::NotImplemented, "unknown action passed"};

    CallAction action = (CallAction) action_idx;

    switch(action) {
        case CallAction::GET_VARIABLES: {
            CallResponse res = parseGetVariables(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleGetVariables(uid, GetVariablesView{obj});
        }

        case CallAction::SET_VARIABLES: {
            CallResponse res = parseSetVariables(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleSetVariables(uid, SetVariablesView{obj});
        }

        case CallAction::GET_BASE_REPORT: {
            CallResponse res = parseGetBaseReport(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleGetBaseReport(uid, GetBaseReportView{obj});
        }

        case CallAction::TRIGGER_MESSAGE: {
            CallResponse res = parseTriggerMessage(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleTriggerMessage(uid, TriggerMessageView{obj});
        }

        case CallAction::RESET: {
            CallResponse res = parseReset(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleReset(uid, ResetView{obj});
        }

        case CallAction::AFRR_SIGNAL:
        case CallAction::AFRR_SIGNAL_RESPONSE:
        case CallAction::ADJUST_PERIODIC_EVENT_STREAM:
        case CallAction::ADJUST_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::AUTHORIZE:
        case CallAction::AUTHORIZE_RESPONSE:
        case CallAction::BATTERY_SWAP:
        case CallAction::BATTERY_SWAP_RESPONSE:
        case CallAction::BOOT_NOTIFICATION:
        case CallAction::BOOT_NOTIFICATION_RESPONSE:
        case CallAction::CANCEL_RESERVATION:
        case CallAction::CANCEL_RESERVATION_RESPONSE:
        case CallAction::CERTIFICATE_SIGNED:
        case CallAction::CERTIFICATE_SIGNED_RESPONSE:
        case CallAction::CHANGE_AVAILABILITY:
        case CallAction::CHANGE_AVAILABILITY_RESPONSE:
        case CallAction::CHANGE_TRANSACTION_TARIFF:
        case CallAction::CHANGE_TRANSACTION_TARIFF_RESPONSE:
        case CallAction::CLEAR_CACHE:
        case CallAction::CLEAR_CACHE_RESPONSE:
        case CallAction::CLEAR_CHARGING_PROFILE:
        case CallAction::CLEAR_CHARGING_PROFILE_RESPONSE:
        case CallAction::CLEAR_DER_CONTROL:
        case CallAction::CLEAR_DER_CONTROL_RESPONSE:
        case CallAction::CLEAR_DISPLAY_MESSAGE:
        case CallAction::CLEAR_DISPLAY_MESSAGE_RESPONSE:
        case CallAction::CLEAR_TARIFFS:
        case CallAction::CLEAR_TARIFFS_RESPONSE:
        case CallAction::CLEAR_VARIABLE_MONITORING:
        case CallAction::CLEAR_VARIABLE_MONITORING_RESPONSE:
        case CallAction::CLEARED_CHARGING_LIMIT:
        case CallAction::CLEARED_CHARGING_LIMIT_RESPONSE:
        case CallAction::CLOSE_PERIODIC_EVENT_STREAM:
        case CallAction::CLOSE_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::COST_UPDATED:
        case CallAction::COST_UPDATED_RESPONSE:
        case CallAction::CUSTOMER_INFORMATION:
        case CallAction::CUSTOMER_INFORMATION_RESPONSE:
        case CallAction::DATA_TRANSFER:
        case CallAction::DATA_TRANSFER_RESPONSE:
        case CallAction::DELETE_CERTIFICATE:
        case CallAction::DELETE_CERTIFICATE_RESPONSE:
        case CallAction::FIRMWARE_STATUS_NOTIFICATION:
        case CallAction::FIRMWARE_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::GET15118_EV_CERTIFICATE:
        case CallAction::GET15118_EV_CERTIFICATE_RESPONSE:
        case CallAction::GET_BASE_REPORT_RESPONSE:
        case CallAction::GET_CERTIFICATE_CHAIN_STATUS:
        case CallAction::GET_CERTIFICATE_CHAIN_STATUS_RESPONSE:
        case CallAction::GET_CERTIFICATE_STATUS:
        case CallAction::GET_CERTIFICATE_STATUS_RESPONSE:
        case CallAction::GET_CHARGING_PROFILES:
        case CallAction::GET_CHARGING_PROFILES_RESPONSE:
        case CallAction::GET_COMPOSITE_SCHEDULE:
        case CallAction::GET_COMPOSITE_SCHEDULE_RESPONSE:
        case CallAction::GET_DER_CONTROL:
        case CallAction::GET_DER_CONTROL_RESPONSE:
        case CallAction::GET_DISPLAY_MESSAGES:
        case CallAction::GET_DISPLAY_MESSAGES_RESPONSE:
        case CallAction::GET_INSTALLED_CERTIFICATE_IDS:
        case CallAction::GET_INSTALLED_CERTIFICATE_IDS_RESPONSE:
        case CallAction::GET_LOCAL_LIST_VERSION:
        case CallAction::GET_LOCAL_LIST_VERSION_RESPONSE:
        case CallAction::GET_LOG:
        case CallAction::GET_LOG_RESPONSE:
        case CallAction::GET_MONITORING_REPORT:
        case CallAction::GET_MONITORING_REPORT_RESPONSE:
        case CallAction::GET_PERIODIC_EVENT_STREAM:
        case CallAction::GET_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::GET_REPORT:
        case CallAction::GET_REPORT_RESPONSE:
        case CallAction::GET_TARIFFS:
        case CallAction::GET_TARIFFS_RESPONSE:
        case CallAction::GET_TRANSACTION_STATUS:
        case CallAction::GET_TRANSACTION_STATUS_RESPONSE:
        case CallAction::GET_VARIABLES_RESPONSE:
        case CallAction::HEARTBEAT:
        case CallAction::HEARTBEAT_RESPONSE:
        case CallAction::INSTALL_CERTIFICATE:
        case CallAction::INSTALL_CERTIFICATE_RESPONSE:
        case CallAction::LOG_STATUS_NOTIFICATION:
        case CallAction::LOG_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::METER_VALUES:
        case CallAction::METER_VALUES_RESPONSE:
        case CallAction::NOTIFY_ALLOWED_ENERGY_TRANSFER:
        case CallAction::NOTIFY_ALLOWED_ENERGY_TRANSFER_RESPONSE:
        case CallAction::NOTIFY_CHARGING_LIMIT:
        case CallAction::NOTIFY_CHARGING_LIMIT_RESPONSE:
        case CallAction::NOTIFY_CUSTOMER_INFORMATION:
        case CallAction::NOTIFY_CUSTOMER_INFORMATION_RESPONSE:
        case CallAction::NOTIFY_DER_ALARM:
        case CallAction::NOTIFY_DER_ALARM_RESPONSE:
        case CallAction::NOTIFY_DER_START_STOP:
        case CallAction::NOTIFY_DER_START_STOP_RESPONSE:
        case CallAction::NOTIFY_DISPLAY_MESSAGES:
        case CallAction::NOTIFY_DISPLAY_MESSAGES_RESPONSE:
        case CallAction::NOTIFY_EV_CHARGING_NEEDS:
        case CallAction::NOTIFY_EV_CHARGING_NEEDS_RESPONSE:
        case CallAction::NOTIFY_EV_CHARGING_SCHEDULE:
        case CallAction::NOTIFY_EV_CHARGING_SCHEDULE_RESPONSE:
        case CallAction::NOTIFY_EVENT:
        case CallAction::NOTIFY_EVENT_RESPONSE:
        case CallAction::NOTIFY_MONITORING_REPORT:
        case CallAction::NOTIFY_MONITORING_REPORT_RESPONSE:
        case CallAction::NOTIFY_PERIODIC_EVENT_STREAM:
        case CallAction::NOTIFY_PRIORITY_CHARGING:
        case CallAction::NOTIFY_PRIORITY_CHARGING_RESPONSE:
        case CallAction::NOTIFY_REPORT:
        case CallAction::NOTIFY_REPORT_RESPONSE:
        case CallAction::NOTIFY_SETTLEMENT:
        case CallAction::NOTIFY_SETTLEMENT_RESPONSE:
        case CallAction::NOTIFY_WEB_PAYMENT_STARTED:
        case CallAction::NOTIFY_WEB_PAYMENT_STARTED_RESPONSE:
        case CallAction::OPEN_PERIODIC_EVENT_STREAM:
        case CallAction::OPEN_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::PUBLISH_FIRMWARE:
        case CallAction::PUBLISH_FIRMWARE_RESPONSE:
        case CallAction::PUBLISH_FIRMWARE_STATUS_NOTIFICATION:
        case CallAction::PUBLISH_FIRMWARE_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::PULL_DYNAMIC_SCHEDULE_UPDATE:
        case CallAction::PULL_DYNAMIC_SCHEDULE_UPDATE_RESPONSE:
        case CallAction::REPORT_CHARGING_PROFILES:
        case CallAction::REPORT_CHARGING_PROFILES_RESPONSE:
        case CallAction::REPORT_DER_CONTROL:
        case CallAction::REPORT_DER_CONTROL_RESPONSE:
        case CallAction::REQUEST_BATTERY_SWAP:
        case CallAction::REQUEST_BATTERY_SWAP_RESPONSE:
        case CallAction::REQUEST_START_TRANSACTION:
        case CallAction::REQUEST_START_TRANSACTION_RESPONSE:
        case CallAction::REQUEST_STOP_TRANSACTION:
        case CallAction::REQUEST_STOP_TRANSACTION_RESPONSE:
        case CallAction::RESERVATION_STATUS_UPDATE:
        case CallAction::RESERVATION_STATUS_UPDATE_RESPONSE:
        case CallAction::RESERVE_NOW:
        case CallAction::RESERVE_NOW_RESPONSE:
        case CallAction::RESET_RESPONSE:
        case CallAction::SECURITY_EVENT_NOTIFICATION:
        case CallAction::SECURITY_EVENT_NOTIFICATION_RESPONSE:
        case CallAction::SEND_LOCAL_LIST:
        case CallAction::SEND_LOCAL_LIST_RESPONSE:
        case CallAction::SET_CHARGING_PROFILE:
        case CallAction::SET_CHARGING_PROFILE_RESPONSE:
        case CallAction::SET_DER_CONTROL:
        case CallAction::SET_DER_CONTROL_RESPONSE:
        case CallAction::SET_DEFAULT_TARIFF:
        case CallAction::SET_DEFAULT_TARIFF_RESPONSE:
        case CallAction::SET_DISPLAY_MESSAGE:
        case CallAction::SET_DISPLAY_MESSAGE_RESPONSE:
        case CallAction::SET_MONITORING_BASE:
        case CallAction::SET_MONITORING_BASE_RESPONSE:
        case CallAction::SET_MONITORING_LEVEL:
        case CallAction::SET_MONITORING_LEVEL_RESPONSE:
        case CallAction::SET_NETWORK_PROFILE:
        case CallAction::SET_NETWORK_PROFILE_RESPONSE:
        case CallAction::SET_VARIABLE_MONITORING:
        case CallAction::SET_VARIABLE_MONITORING_RESPONSE:
        case CallAction::SET_VARIABLES_RESPONSE:
        case CallAction::SIGN_CERTIFICATE:
        case CallAction::SIGN_CERTIFICATE_RESPONSE:
        case CallAction::STATUS_NOTIFICATION:
        case CallAction::STATUS_NOTIFICATION_RESPONSE:
        case CallAction::TRANSACTION_EVENT:
        case CallAction::TRANSACTION_EVENT_RESPONSE:
        case CallAction::TRIGGER_MESSAGE_RESPONSE:
        case CallAction::UNLOCK_CONNECTOR:
        case CallAction::UNLOCK_CONNECTOR_RESPONSE:
        case CallAction::UNPUBLISH_FIRMWARE:
        case CallAction::UNPUBLISH_FIRMWARE_RESPONSE:
        case CallAction::UPDATE_DYNAMIC_SCHEDULE:
        case CallAction::UPDATE_DYNAMIC_SCHEDULE_RESPONSE:
        case CallAction::UPDATE_FIRMWARE:
        case CallAction::UPDATE_FIRMWARE_RESPONSE:
        case CallAction::USE_PRIORITY_CHARGING:
        case CallAction::USE_PRIORITY_CHARGING_RESPONSE:
        case CallAction::VAT_NUMBER_VALIDATION:
        case CallAction::VAT_NUMBER_VALIDATION_RESPONSE:
            return CallResponse{CallErrorCode::NotSupported, "action not supported"};
    }

    SILENCE_GCC_UNREACHABLE();
}

CallResponse callResultHandler(int32_t connectorId, CallAction resultTo, JsonObject obj, ChargePoint21 *cp) {

    switch(resultTo) {
        case CallAction::BOOT_NOTIFICATION: {
            CallResponse res = parseBootNotificationResponse(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleBootNotificationResponse(connectorId, BootNotificationResponseView{obj});
        }

        case CallAction::HEARTBEAT: {
            CallResponse res = parseHeartbeatResponse(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleHeartbeatResponse(connectorId, HeartbeatResponseView{obj});
        }

        case CallAction::STATUS_NOTIFICATION: {
            CallResponse res = parseStatusNotificationResponse(obj);
            if (res.result != CallErrorCode::OK)
                return res;

            return cp->handleStatusNotificationResponse(connectorId, StatusNotificationResponseView{obj});
        }

        case CallAction::AFRR_SIGNAL:
        case CallAction::AFRR_SIGNAL_RESPONSE:
        case CallAction::ADJUST_PERIODIC_EVENT_STREAM:
        case CallAction::ADJUST_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::AUTHORIZE:
        case CallAction::AUTHORIZE_RESPONSE:
        case CallAction::BATTERY_SWAP:
        case CallAction::BATTERY_SWAP_RESPONSE:
        case CallAction::BOOT_NOTIFICATION_RESPONSE:
        case CallAction::CANCEL_RESERVATION:
        case CallAction::CANCEL_RESERVATION_RESPONSE:
        case CallAction::CERTIFICATE_SIGNED:
        case CallAction::CERTIFICATE_SIGNED_RESPONSE:
        case CallAction::CHANGE_AVAILABILITY:
        case CallAction::CHANGE_AVAILABILITY_RESPONSE:
        case CallAction::CHANGE_TRANSACTION_TARIFF:
        case CallAction::CHANGE_TRANSACTION_TARIFF_RESPONSE:
        case CallAction::CLEAR_CACHE:
        case CallAction::CLEAR_CACHE_RESPONSE:
        case CallAction::CLEAR_CHARGING_PROFILE:
        case CallAction::CLEAR_CHARGING_PROFILE_RESPONSE:
        case CallAction::CLEAR_DER_CONTROL:
        case CallAction::CLEAR_DER_CONTROL_RESPONSE:
        case CallAction::CLEAR_DISPLAY_MESSAGE:
        case CallAction::CLEAR_DISPLAY_MESSAGE_RESPONSE:
        case CallAction::CLEAR_TARIFFS:
        case CallAction::CLEAR_TARIFFS_RESPONSE:
        case CallAction::CLEAR_VARIABLE_MONITORING:
        case CallAction::CLEAR_VARIABLE_MONITORING_RESPONSE:
        case CallAction::CLEARED_CHARGING_LIMIT:
        case CallAction::CLEARED_CHARGING_LIMIT_RESPONSE:
        case CallAction::CLOSE_PERIODIC_EVENT_STREAM:
        case CallAction::CLOSE_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::COST_UPDATED:
        case CallAction::COST_UPDATED_RESPONSE:
        case CallAction::CUSTOMER_INFORMATION:
        case CallAction::CUSTOMER_INFORMATION_RESPONSE:
        case CallAction::DATA_TRANSFER:
        case CallAction::DATA_TRANSFER_RESPONSE:
        case CallAction::DELETE_CERTIFICATE:
        case CallAction::DELETE_CERTIFICATE_RESPONSE:
        case CallAction::FIRMWARE_STATUS_NOTIFICATION:
        case CallAction::FIRMWARE_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::GET15118_EV_CERTIFICATE:
        case CallAction::GET15118_EV_CERTIFICATE_RESPONSE:
        case CallAction::GET_BASE_REPORT:
        case CallAction::GET_BASE_REPORT_RESPONSE:
        case CallAction::GET_CERTIFICATE_CHAIN_STATUS:
        case CallAction::GET_CERTIFICATE_CHAIN_STATUS_RESPONSE:
        case CallAction::GET_CERTIFICATE_STATUS:
        case CallAction::GET_CERTIFICATE_STATUS_RESPONSE:
        case CallAction::GET_CHARGING_PROFILES:
        case CallAction::GET_CHARGING_PROFILES_RESPONSE:
        case CallAction::GET_COMPOSITE_SCHEDULE:
        case CallAction::GET_COMPOSITE_SCHEDULE_RESPONSE:
        case CallAction::GET_DER_CONTROL:
        case CallAction::GET_DER_CONTROL_RESPONSE:
        case CallAction::GET_DISPLAY_MESSAGES:
        case CallAction::GET_DISPLAY_MESSAGES_RESPONSE:
        case CallAction::GET_INSTALLED_CERTIFICATE_IDS:
        case CallAction::GET_INSTALLED_CERTIFICATE_IDS_RESPONSE:
        case CallAction::GET_LOCAL_LIST_VERSION:
        case CallAction::GET_LOCAL_LIST_VERSION_RESPONSE:
        case CallAction::GET_LOG:
        case CallAction::GET_LOG_RESPONSE:
        case CallAction::GET_MONITORING_REPORT:
        case CallAction::GET_MONITORING_REPORT_RESPONSE:
        case CallAction::GET_PERIODIC_EVENT_STREAM:
        case CallAction::GET_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::GET_REPORT:
        case CallAction::GET_REPORT_RESPONSE:
        case CallAction::GET_TARIFFS:
        case CallAction::GET_TARIFFS_RESPONSE:
        case CallAction::GET_TRANSACTION_STATUS:
        case CallAction::GET_TRANSACTION_STATUS_RESPONSE:
        case CallAction::GET_VARIABLES:
        case CallAction::GET_VARIABLES_RESPONSE:
        case CallAction::HEARTBEAT_RESPONSE:
        case CallAction::INSTALL_CERTIFICATE:
        case CallAction::INSTALL_CERTIFICATE_RESPONSE:
        case CallAction::LOG_STATUS_NOTIFICATION:
        case CallAction::LOG_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::METER_VALUES:
        case CallAction::METER_VALUES_RESPONSE:
        case CallAction::NOTIFY_ALLOWED_ENERGY_TRANSFER:
        case CallAction::NOTIFY_ALLOWED_ENERGY_TRANSFER_RESPONSE:
        case CallAction::NOTIFY_CHARGING_LIMIT:
        case CallAction::NOTIFY_CHARGING_LIMIT_RESPONSE:
        case CallAction::NOTIFY_CUSTOMER_INFORMATION:
        case CallAction::NOTIFY_CUSTOMER_INFORMATION_RESPONSE:
        case CallAction::NOTIFY_DER_ALARM:
        case CallAction::NOTIFY_DER_ALARM_RESPONSE:
        case CallAction::NOTIFY_DER_START_STOP:
        case CallAction::NOTIFY_DER_START_STOP_RESPONSE:
        case CallAction::NOTIFY_DISPLAY_MESSAGES:
        case CallAction::NOTIFY_DISPLAY_MESSAGES_RESPONSE:
        case CallAction::NOTIFY_EV_CHARGING_NEEDS:
        case CallAction::NOTIFY_EV_CHARGING_NEEDS_RESPONSE:
        case CallAction::NOTIFY_EV_CHARGING_SCHEDULE:
        case CallAction::NOTIFY_EV_CHARGING_SCHEDULE_RESPONSE:
        case CallAction::NOTIFY_EVENT:
        case CallAction::NOTIFY_EVENT_RESPONSE:
        case CallAction::NOTIFY_MONITORING_REPORT:
        case CallAction::NOTIFY_MONITORING_REPORT_RESPONSE:
        case CallAction::NOTIFY_PERIODIC_EVENT_STREAM:
        case CallAction::NOTIFY_PRIORITY_CHARGING:
        case CallAction::NOTIFY_PRIORITY_CHARGING_RESPONSE:
        case CallAction::NOTIFY_REPORT:
        case CallAction::NOTIFY_REPORT_RESPONSE:
        case CallAction::NOTIFY_SETTLEMENT:
        case CallAction::NOTIFY_SETTLEMENT_RESPONSE:
        case CallAction::NOTIFY_WEB_PAYMENT_STARTED:
        case CallAction::NOTIFY_WEB_PAYMENT_STARTED_RESPONSE:
        case CallAction::OPEN_PERIODIC_EVENT_STREAM:
        case CallAction::OPEN_PERIODIC_EVENT_STREAM_RESPONSE:
        case CallAction::PUBLISH_FIRMWARE:
        case CallAction::PUBLISH_FIRMWARE_RESPONSE:
        case CallAction::PUBLISH_FIRMWARE_STATUS_NOTIFICATION:
        case CallAction::PUBLISH_FIRMWARE_STATUS_NOTIFICATION_RESPONSE:
        case CallAction::PULL_DYNAMIC_SCHEDULE_UPDATE:
        case CallAction::PULL_DYNAMIC_SCHEDULE_UPDATE_RESPONSE:
        case CallAction::REPORT_CHARGING_PROFILES:
        case CallAction::REPORT_CHARGING_PROFILES_RESPONSE:
        case CallAction::REPORT_DER_CONTROL:
        case CallAction::REPORT_DER_CONTROL_RESPONSE:
        case CallAction::REQUEST_BATTERY_SWAP:
        case CallAction::REQUEST_BATTERY_SWAP_RESPONSE:
        case CallAction::REQUEST_START_TRANSACTION:
        case CallAction::REQUEST_START_TRANSACTION_RESPONSE:
        case CallAction::REQUEST_STOP_TRANSACTION:
        case CallAction::REQUEST_STOP_TRANSACTION_RESPONSE:
        case CallAction::RESERVATION_STATUS_UPDATE:
        case CallAction::RESERVATION_STATUS_UPDATE_RESPONSE:
        case CallAction::RESERVE_NOW:
        case CallAction::RESERVE_NOW_RESPONSE:
        case CallAction::RESET:
        case CallAction::RESET_RESPONSE:
        case CallAction::SECURITY_EVENT_NOTIFICATION:
        case CallAction::SECURITY_EVENT_NOTIFICATION_RESPONSE:
        case CallAction::SEND_LOCAL_LIST:
        case CallAction::SEND_LOCAL_LIST_RESPONSE:
        case CallAction::SET_CHARGING_PROFILE:
        case CallAction::SET_CHARGING_PROFILE_RESPONSE:
        case CallAction::SET_DER_CONTROL:
        case CallAction::SET_DER_CONTROL_RESPONSE:
        case CallAction::SET_DEFAULT_TARIFF:
        case CallAction::SET_DEFAULT_TARIFF_RESPONSE:
        case CallAction::SET_DISPLAY_MESSAGE:
        case CallAction::SET_DISPLAY_MESSAGE_RESPONSE:
        case CallAction::SET_MONITORING_BASE:
        case CallAction::SET_MONITORING_BASE_RESPONSE:
        case CallAction::SET_MONITORING_LEVEL:
        case CallAction::SET_MONITORING_LEVEL_RESPONSE:
        case CallAction::SET_NETWORK_PROFILE:
        case CallAction::SET_NETWORK_PROFILE_RESPONSE:
        case CallAction::SET_VARIABLE_MONITORING:
        case CallAction::SET_VARIABLE_MONITORING_RESPONSE:
        case CallAction::SET_VARIABLES:
        case CallAction::SET_VARIABLES_RESPONSE:
        case CallAction::SIGN_CERTIFICATE:
        case CallAction::SIGN_CERTIFICATE_RESPONSE:
        case CallAction::STATUS_NOTIFICATION_RESPONSE:
        case CallAction::TRANSACTION_EVENT:
        case CallAction::TRANSACTION_EVENT_RESPONSE:
        case CallAction::TRIGGER_MESSAGE:
        case CallAction::TRIGGER_MESSAGE_RESPONSE:
        case CallAction::UNLOCK_CONNECTOR:
        case CallAction::UNLOCK_CONNECTOR_RESPONSE:
        case CallAction::UNPUBLISH_FIRMWARE:
        case CallAction::UNPUBLISH_FIRMWARE_RESPONSE:
        case CallAction::UPDATE_DYNAMIC_SCHEDULE:
        case CallAction::UPDATE_DYNAMIC_SCHEDULE_RESPONSE:
        case CallAction::UPDATE_FIRMWARE:
        case CallAction::UPDATE_FIRMWARE_RESPONSE:
        case CallAction::USE_PRIORITY_CHARGING:
        case CallAction::USE_PRIORITY_CHARGING_RESPONSE:
        case CallAction::VAT_NUMBER_VALIDATION:
        case CallAction::VAT_NUMBER_VALIDATION_RESPONSE:
            return CallResponse{CallErrorCode::NotSupported, "action not supported"};
    }

    SILENCE_GCC_UNREACHABLE();
}

} // namespace Ocpp21
