from statham.schema.constants import Maybe
from statham.schema.elements import Object, String
from statham.schema.property import Property


class CustomDataType(Object):
    """This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data."""

    vendorId: str = Property(String(maxLength=255), required=True)


class NotifySettlementResponse(Object, additionalProperties=False):

    receiptUrl: Maybe[str] = Property(String(maxLength=2000, description='The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.\r\n\r\n'))

    receiptId: Maybe[str] = Property(String(maxLength=50, description='The receipt id if the receipt is generated by CSMS.\r\n\r\n'))

    customData: Maybe[CustomDataType] = Property(CustomDataType)
