from statham.schema.constants import Maybe
from statham.schema.elements import Number, Object, String
from statham.schema.property import Property


class CustomDataType(Object):
    """This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data."""

    vendorId: str = Property(String(maxLength=255), required=True)


class AddressType(Object, additionalProperties=False):
    """*(2.1)* A generic address format.
"""

    name: str = Property(String(maxLength=50, description='Name of person/company\r\n'), required=True)

    address1: str = Property(String(maxLength=100, description='Address line 1\r\n'), required=True)

    address2: Maybe[str] = Property(String(maxLength=100, description='Address line 2\r\n'))

    city: str = Property(String(maxLength=100, description='City\r\n'), required=True)

    postalCode: Maybe[str] = Property(String(maxLength=20, description='Postal code\r\n'))

    country: str = Property(String(maxLength=50, description='Country name\r\n'), required=True)

    customData: Maybe[CustomDataType] = Property(CustomDataType)


class NotifySettlementRequest(Object, additionalProperties=False):

    transactionId: Maybe[str] = Property(String(maxLength=36, description='The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.\r\n\r\n'))

    pspRef: str = Property(String(maxLength=255, description='The payment reference received from the payment terminal and is used as the value for _idToken_. \r\n\r\n'), required=True)

    status: str = Property(String(enum=['Settled', 'Canceled', 'Rejected', 'Failed'], description='The status of the settlement attempt.\r\n\r\n'), required=True)

    statusInfo: Maybe[str] = Property(String(maxLength=500, description='Additional information from payment terminal/payment process.\r\n\r\n'))

    settlementAmount: float = Property(Number(description='The amount that was settled, or attempted to be settled (in case of failure).\r\n\r\n'), required=True)

    settlementTime: str = Property(String(format='date-time', description='The time when the settlement was done.\r\n\r\n'), required=True)

    receiptId: Maybe[str] = Property(String(maxLength=50))

    receiptUrl: Maybe[str] = Property(String(maxLength=2000, description='The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.\r\n\r\n'))

    vatCompany: Maybe[AddressType] = Property(AddressType)

    vatNumber: Maybe[str] = Property(String(maxLength=20, description='VAT number for a company receipt.\r\n\r\n'))

    customData: Maybe[CustomDataType] = Property(CustomDataType)
