#pragma once

#ifndef NUM_CONNECTORS
#define NUM_CONNECTORS 1
#endif


#ifndef CURRENT_REQUIRED_TO_START_CHARGING
#define CURRENT_REQUIRED_TO_START_CHARGING 6
#endif

#ifndef LINE_VOLTAGE
#define LINE_VOLTAGE 230
#endif

// Default configuration

#ifndef DEFAULT_ALLOW_OFFLINE_TX_FOR_UNKNOWN_ID
#define DEFAULT_ALLOW_OFFLINE_TX_FOR_UNKNOWN_ID false
#endif

#ifndef DEFAULT_AUTHORIZATION_CACHE_ENABLED
#define DEFAULT_AUTHORIZATION_CACHE_ENABLED false
#endif

#ifndef DEFAULT_AUTHORIZE_REMOTE_TX_REQUESTS
#define DEFAULT_AUTHORIZE_REMOTE_TX_REQUESTS false
#endif

#ifndef DEFAULT_BLINK_REPEAT
#define DEFAULT_BLINK_REPEAT 3
#endif

#ifndef DEFAULT_CLOCK_ALIGNED_DATA_INTERVAL
#define DEFAULT_CLOCK_ALIGNED_DATA_INTERVAL 0
#endif

#ifndef DEFAULT_CONNECTION_TIME_OUT
#define DEFAULT_CONNECTION_TIME_OUT 60
#endif

#ifndef DEFAULT_CONNECTOR_PHASE_ROTATION
#define DEFAULT_CONNECTOR_PHASE_ROTATION "1.Unknown"
#endif


#ifndef DEFAULT_HEARTBEAT_INTERVAL_S
#define DEFAULT_HEARTBEAT_INTERVAL_S 60
#endif

#ifndef DEFAULT_LIGHT_INTENSITY
#define DEFAULT_LIGHT_INTENSITY 100
#endif

#ifndef DEFAULT_LOCAL_AUTHORIZE_OFFLINE
#define DEFAULT_LOCAL_AUTHORIZE_OFFLINE false
#endif

#ifndef DEFAULT_LOCAL_PRE_AUTHORIZE
#define DEFAULT_LOCAL_PRE_AUTHORIZE false
#endif

#ifndef DEFAULT_MAX_ENERGY_ON_INVALID_ID
#define DEFAULT_MAX_ENERGY_ON_INVALID_ID 0
#endif

#ifndef DEFAULT_MESSAGE_TIMEOUT
#define DEFAULT_MESSAGE_TIMEOUT 10
#endif

#ifndef DEFAULT_METER_VALUES_ALIGNED_DATA
#define DEFAULT_METER_VALUES_ALIGNED_DATA ""
#endif

#ifndef METER_VALUES_ALIGNED_DATA_MAX_LENGTH
#define METER_VALUES_ALIGNED_DATA_MAX_LENGTH 5
#endif

#ifndef DEFAULT_METER_VALUES_SAMPLED_DATA
#define DEFAULT_METER_VALUES_SAMPLED_DATA ""
#endif

#ifndef METER_VALUES_SAMPLED_DATA_MAX_LENGTH
#define METER_VALUES_SAMPLED_DATA_MAX_LENGTH 5
#endif

#ifndef DEFAULT_METER_VALUE_SAMPLE_INTERVAL
#define DEFAULT_METER_VALUE_SAMPLE_INTERVAL 0
#endif

#ifndef DEFAULT_MINIMUM_STATUS_DURATION
#define DEFAULT_MINIMUM_STATUS_DURATION 1
#endif

#ifndef DEFAULT_RESET_RETRIES
#define DEFAULT_RESET_RETRIES 1
#endif

#ifndef DEFAULT_STOP_TRANSACTION_ON_EV_SIDE_DISCONNECT
#define DEFAULT_STOP_TRANSACTION_ON_EV_SIDE_DISCONNECT false
#endif

#ifndef DEFAULT_STOP_TRANSACTION_ON_INVALID_ID
#define DEFAULT_STOP_TRANSACTION_ON_INVALID_ID false
#endif

#ifndef STOP_TRANSACTION_MAX_METER_VALUES
#define STOP_TRANSACTION_MAX_METER_VALUES 2
#endif

//#ifndef DEFAULT_STOP_TXN_ALIGNED_DATA
//#define DEFAULT_STOP_TXN_ALIGNED_DATA ""
//#endif

//#ifndef STOP_TXN_ALIGNED_DATA_MAX_LENGTH
//#define STOP_TXN_ALIGNED_DATA_MAX_LENGTH 0
//#endif

//#ifndef DEFAULT_STOP_TXN_SAMPLED_DATA
//#define DEFAULT_STOP_TXN_SAMPLED_DATA ""
//#endif

//#ifndef STOP_TXN_SAMPLED_DATA_MAX_LENGTH
//#define STOP_TXN_SAMPLED_DATA_MAX_LENGTH 0
//#endif

#ifndef SUPPORTED_FEATURE_PROFILES
#define SUPPORTED_FEATURE_PROFILES "Core,SmartCharging"
#endif

//#ifndef SUPPORTED_FEATURE_PROFILES_MAX_LENGTH
//#define SUPPORTED_FEATURE_PROFILES_MAX_LENGTH
//#endif

#ifndef DEFAULT_TRANSACTION_MESSAGE_ATTEMPTS
#define DEFAULT_TRANSACTION_MESSAGE_ATTEMPTS 3
#endif

#ifndef DEFAULT_TRANSACTION_MESSAGE_RETRY_INTERVAL
#define DEFAULT_TRANSACTION_MESSAGE_RETRY_INTERVAL 10
#endif

#ifndef DEFAULT_UNLOCK_CONNECTOR_ON_EV_SIDE_DISCONNECT
#define DEFAULT_UNLOCK_CONNECTOR_ON_EV_SIDE_DISCONNECT false
#endif

#ifndef DEFAULT_WEB_SOCKET_PING_INTERVAL
#define DEFAULT_WEB_SOCKET_PING_INTERVAL 10
#endif


//#ifndef DEFAULT_LOCAL_AUTH_LIST_ENABLED
//#define DEFAULT_LOCAL_AUTH_LIST_ENABLED
//#endif

//#ifndef DEFAULT_LOCAL_AUTH_LIST_MAX_LENGTH
//#define DEFAULT_LOCAL_AUTH_LIST_MAX_LENGTH
//#endif

//#ifndef DEFAULT_SEND_LOCAL_LIST_MAX_LENGTH
//#define DEFAULT_SEND_LOCAL_LIST_MAX_LENGTH
//#endif


//#ifndef DEFAULT_RESERVE_CONNECTOR_ZERO_SUPPORTED
//#define DEFAULT_RESERVE_CONNECTOR_ZERO_SUPPORTED
//#endif


#ifndef CHARGE_PROFILE_MAX_STACK_LEVEL
#define CHARGE_PROFILE_MAX_STACK_LEVEL 3
#endif

#ifndef CHARGING_SCHEDULE_ALLOWED_CHARGING_RATE_UNIT
#define CHARGING_SCHEDULE_ALLOWED_CHARGING_RATE_UNIT "Current"
#endif

#ifndef CHARGING_SCHEDULE_MAX_PERIODS
#define CHARGING_SCHEDULE_MAX_PERIODS 3
#endif

#ifndef GET_COMPOSITE_SCHEDULE_MAX_PERIODS
#define GET_COMPOSITE_SCHEDULE_MAX_PERIODS (CHARGING_SCHEDULE_MAX_PERIODS * NUM_CONNECTORS * CHARGE_PROFILE_MAX_STACK_LEVEL * 2)
#endif

#ifndef CONNECTOR_SWITCH3TO1_PHASE_SUPPORTED
#define CONNECTOR_SWITCH3TO1_PHASE_SUPPORTED false
#endif

#ifndef MAX_CHARGING_PROFILES_INSTALLED
#define MAX_CHARGING_PROFILES_INSTALLED 3
#endif
