language: c

matrix:
  include:
    - osx_image: xcode9.1
      compiler: clang
      os: osx
      env:
        - DISTRO=osx:xcode9.1
        - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig
        - PYTHONPATH=/usr/local/lib/python3.6/site-packages

compiler:
  - clang
  - gcc

os: linux
sudo: required
services: docker
env:
  matrix:
    - DISTRO=fedora:rawhide
    - DISTRO=fedora:latest
    - DISTRO=debian:unstable
    - DISTRO=debian:testing
    - DISTRO=ubuntu:devel

before_install:
  - . .travis.functions; docker_start

install:
  - . .travis.functions; docker_exec ./.travis.install

script:
  - . .travis.functions; docker_exec ./.travis.script

after_script:
  - . .travis.functions; docker_stop
